# This is a basic workflow to help you get started with Actions
name: 🚀 Deploy website on push on master

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: giacomocorallini.com
          username: ftp@giacomocorallini.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: giacomocorallini.com/public_html/
          exclude: .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*

